import { Project } from "../types";

export const PROJECTS: Project[] = [
  {
    title: 'Food Ordering App',
    date: 'Jun 2024',
    subtext: 'A mobile food-ordering app built with Kotlin, XML and SQL, featuring user authentication, multi-order handling and secure cash payments for a seamless checkout experience.',
    icon: '🍔',
    type: 'Android app',
    tagline: 'A native Android food-ordering app with accounts, multi-order carts and secure checkout.',
    tech: ['Kotlin', 'XML', 'SQL', 'Android'],
    flowTitle: 'HOW IT WORKS',
    flow: [
      { label: 'Sign in', sub: 'auth' },
      { label: 'Browse menu', sub: 'catalog' },
      { label: 'Cart', sub: 'multi-order' },
      { label: 'Checkout', sub: 'cash payment' },
      { label: 'Order history', sub: 'SQL store' },
    ],
    flowCaption: 'From sign-in to order history, every step is backed by a local SQL store.',
    sections: [
      { heading: 'PROBLEM', body: 'Small food-ordering apps are often clunky — no persistent accounts, one order at a time, and fragile data handling that loses state between sessions.' },
      { heading: 'SOLUTION', body: 'A native Kotlin app with user authentication, a cart that handles multiple simultaneous orders, and cash-on-delivery checkout, all persisted to a local SQL database.' },
      { heading: 'INSIGHT', body: 'Modelling the cart as multi-order state up front — instead of a single active order — kept checkout reliable even with several items in flight.' },
      { heading: 'BUILT WITH', body: 'Kotlin and XML layouts on Android, with a SQL database for accounts, orders and history.' },
      { heading: "WHERE IT'S GOING", body: 'Online payment methods and push notifications for live order status.' },
    ],
  },
  {
    title: 'Healthcare System',
    date: 'Sep 2024',
    subtext: 'A scalable healthcare management system built with Python and MySQL to streamline patient registration, appointment scheduling and doctor access, with robust data validation.',
    icon: '🏥',
    type: 'Management system',
    tagline: 'A registration and scheduling system that streamlines patient–doctor workflows.',
    tech: ['Python', 'MySQL'],
    flowTitle: 'HOW IT WORKS',
    flow: [
      { label: 'Register patient', sub: 'intake' },
      { label: 'Book appointment', sub: 'scheduling' },
      { label: 'Doctor access', sub: 'lookup' },
      { label: 'Validate', sub: 'data checks' },
      { label: 'Records', sub: 'MySQL' },
    ],
    flowCaption: 'A single flow for registration, scheduling and doctor access over one data store.',
    sections: [
      { heading: 'PROBLEM', body: 'Small clinics juggle patient registration, appointments and doctor access across disconnected tools, which invites double-bookings and data errors.' },
      { heading: 'SOLUTION', body: 'A Python and MySQL system that centralises patient registration, appointment scheduling and doctor access behind clean, intuitive interfaces.' },
      { heading: 'INSIGHT', body: 'Enforcing strong validation at the point of entry prevented most of the downstream scheduling conflicts before they happened.' },
      { heading: 'BUILT WITH', body: 'Python for the application logic and MySQL for patients, appointments and access records.' },
      { heading: "WHERE IT'S GOING", body: 'Role-based access control and a web front-end so staff can work from any device.' },
    ],
  },
  {
    title: 'Facial Emotion AI',
    date: 'Jan 2025',
    subtext: 'A real-time emotion recognition system using OpenCV and a CNN deep-learning model, with an optimised inference pipeline tuned for high accuracy and low latency.',
    icon: '🧠',
    type: 'Computer vision',
    tagline: 'Real-time emotion recognition from a webcam using OpenCV and a CNN.',
    tech: ['Python', 'OpenCV', 'CNN', 'Deep Learning'],
    flowTitle: 'HOW IT WORKS',
    flow: [
      { label: 'Camera feed', sub: 'live frames' },
      { label: 'Face detection', sub: 'OpenCV' },
      { label: 'Preprocess', sub: 'normalise' },
      { label: 'CNN classifier', sub: 'inference' },
      { label: 'Emotion', sub: 'prediction' },
    ],
    flowCaption: 'A live pipeline from raw frames to an emotion label, tuned for low latency.',
    sections: [
      { heading: 'PROBLEM', body: 'Emotion recognition has to run live from a camera without lag, while staying accurate across faces and lighting.' },
      { heading: 'SOLUTION', body: 'A pipeline that detects faces with OpenCV, preprocesses each frame and classifies emotion with a CNN, optimised end-to-end for real-time use.' },
      { heading: 'INSIGHT', body: 'Most of the speed-up came from tightening the preprocessing and inference pipeline — not from reaching for a larger model.' },
      { heading: 'BUILT WITH', body: 'Python with OpenCV for detection and a CNN deep-learning model for classification.' },
      { heading: "WHERE IT'S GOING", body: 'A wider set of emotion classes and on-device deployment for offline use.' },
    ],
  },
  {
    title: 'Dice Duel',
    date: 'Jul 2025',
    subtext: 'A turn-based, probability-driven mobile game built with React Native, Expo and Firebase Firestore — betting mechanics, a 2×/4× multiplier reward system and real-time local and AI multiplayer.',
    icon: '🎲',
    type: 'Mobile game · Jabsz Gaming',
    tagline: 'A turn-based, probability-driven dice game with betting and real-time multiplayer.',
    tech: ['React Native', 'Expo', 'Firebase Firestore'],
    flowTitle: 'HOW IT WORKS',
    flow: [
      { label: 'Place bet', sub: 'stake' },
      { label: 'Predict roll', sub: 'player call' },
      { label: 'Dice roll', sub: 'probability' },
      { label: 'Multiplier', sub: '2× / 4×' },
      { label: 'Rewards', sub: 'payout' },
      { label: 'Sync', sub: 'Firestore' },
      { label: 'Opponent', sub: 'local / AI' },
    ],
    flowCaption: 'Built during the Jabsz Gaming internship — full loop from bet to reward, synced in real time.',
    sections: [
      { heading: 'PROBLEM', body: 'A betting dice game needs fair odds, reliable state and smooth multiplayer — both against a local player and against AI.' },
      { heading: 'SOLUTION', body: 'Core game logic covering betting, dice-roll prediction and a 2×/4× multiplier reward system, plus real-time state management for local and AI multiplayer.' },
      { heading: 'INSIGHT', body: 'Centralising game state in Firebase Firestore gave reliable session continuity, so matches survive reconnects without losing progress.' },
      { heading: 'BUILT WITH', body: 'React Native and Expo on the client, with Firebase Firestore for persistent storage and backend synchronisation.' },
      { heading: "WHERE IT'S GOING", body: 'Online player-vs-player matchmaking and global leaderboards.' },
    ],
  },
  {
    title: 'Conversational AI',
    date: 'Apr 2026',
    subtext: 'A multi-turn, context-aware customer-support chatbot with intent recognition, entity extraction and dialogue state tracking, powered by fine-tuned Hugging Face transformers on a Flask/FastAPI and Chainlit stack.',
    icon: '💬',
    type: 'AI system',
    tagline: 'A context-aware, multi-turn support assistant that remembers the whole conversation.',
    tech: ['Hugging Face', 'FastAPI', 'Flask', 'Chainlit', 'NLP'],
    flowTitle: 'HOW IT WORKS',
    flow: [
      { label: 'User message', sub: 'chat input' },
      { label: 'Intent recognition', sub: 'classifier' },
      { label: 'Entity extraction', sub: 'NER' },
      { label: 'Dialogue state', sub: 'context memory' },
      { label: 'Transformer', sub: 'FastAPI serving' },
      { label: 'Chainlit reply', sub: 'grounded answer' },
      { label: 'KB retrieval', sub: 'roadmap', muted: true },
      { label: 'Human handoff', sub: 'roadmap', muted: true },
    ],
    flowCaption: 'The core loop today: context-aware, multi-turn answers over a support domain.',
    sections: [
      { heading: 'PROBLEM', body: 'Support chatbots usually forget what you just said. Every message is treated in isolation, so users repeat themselves and get generic, out-of-context replies.' },
      { heading: 'SOLUTION', body: 'A multi-turn assistant that tracks dialogue state across the conversation, recognises intent and extracts entities, so each answer builds on everything said before it.' },
      { heading: 'INSIGHT', body: 'Most of the answer quality came from state tracking, not model size — reliably remembering context matters more than a bigger network.' },
      { heading: 'WHAT EXISTS TODAY', body: 'Fine-tuned Hugging Face transformers for intent and entity extraction, a Flask/FastAPI backend, and a Chainlit chat UI handling live multi-turn conversations.' },
      { heading: "WHERE IT'S GOING", body: 'Retrieval over a company knowledge base for grounded answers, and automatic handoff to a human agent when the model’s confidence drops.' },
    ],
  },
];
